# Generated by Django 4.0 on 2023-08-13 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creating_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Threads_creating_user', to='auth.user')),
            ],
            options={
                'db_table': 'myapp_threads',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='UserDetails', serialize=False, to='auth.user')),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='')),
                ('profile_image_thumb', models.FileField(blank=True, null=True, upload_to='')),
                ('about_me', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_user_details',
            },
        ),
        migrations.CreateModel(
            name='UserStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserStatuses', to='auth.user')),
            ],
            options={
                'db_table': 'myapp_user_statuses',
            },
        ),
        migrations.CreateModel(
            name='UserGalleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.FileField(upload_to='')),
                ('gallery_image_thumb', models.FileField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserGalleries', to='auth.user')),
            ],
            options={
                'db_table': 'myapp_user_galleries',
            },
        ),
        migrations.CreateModel(
            name='ThreadMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creating_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ThreadMessages', to='auth.user')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ThreadMessages', to='myapp.threads')),
            ],
            options={
                'db_table': 'myapp_thread_messages',
            },
        ),
        migrations.CreateModel(
            name='UserThreadJunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserThreadsJunction', to='myapp.threads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserThreadsJunction', to='auth.user')),
            ],
            options={
                'db_table': 'myapp_user_thread_junctions',
                'unique_together': {('user', 'thread')},
            },
        ),
        migrations.CreateModel(
            name='UserConnectionJunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserConnectionsJunction_user', to='auth.user')),
                ('user_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserConnectionsJunction_user_connection', to='auth.user')),
            ],
            options={
                'db_table': 'myapp_user_connection_junctions',
                'unique_together': {('user', 'user_connection')},
            },
        ),
    ]
